server:
  port: 2103
  mode: "dev"
  host: "localhost"
  grpc_port: 2203

database:
  driver: "postgres"
  host: "localhost"
  port: 2011
  username: "admin"
  password: "admin"
  database: "billing"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 300

redis:
  addrs:
    - "localhost:2005"
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5
  pool_timeout: 5
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  max_retries: 3
  min_retry_backoff: 300
  max_retry_backoff: 500

jwt:
  secret: "${JWT_SECRET}"
  public_key_path: "./certs/public_key.pem"
