server:
  port: 2101
  mode: "dev"
  host: "localhost"

wide_column:
  hosts:
    - "localhost"
  port: 2002
  keyspace: "redirection_ks"
  username: ""
  password: ""
  timeout: 10
  retries: 3

redis:
  addrs:
    - "localhost:2005"
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5
  pool_timeout: 5
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  max_retries: 3
  min_retry_backoff: 300
  max_retry_backoff: 500

kafka:
  brokers:
     - localhost:2008
  flush_frequency: 500
  flush_bytes: 16384
  max_message_bytes: 1000000
  timeout: 10
  max_retries: 3
  retry_backoff: 100
  max_processing_time: 600
  consumer_batch_size: 100
  consumer_batch_interval: 1000