server:
  port: 2104
  mode: "dev"
  host: "localhost"

services:
  identity_service:
    host: "localhost"
    port: 2202
  billing_service:
    host: "localhost"
    port: 2203
  payment_service:
    host: "localhost"
    port: 2204

logger:
  log_level: debug
  file_log_name: "./storages/logs/app.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true