server:
  port: 2102
  mode: "dev"
  host: "localhost"

kafka:
  brokers:
     - "localhost:29092"
  flush_frequency: 500
  flush_bytes: 16384
  max_message_bytes: 1000000
  timeout: 10
  max_retries: 3
  retry_backoff: 100
  max_processing_time: 600
  consumer_batch_size: 100
  consumer_batch_interval: 1000

database:
  driver: "postgres"
  host: "localhost"
  port: 2011
  username: "admin"
  password: "admin"
  database: "identity"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 300